// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hans');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "添加注释";
Blockly.Msg.AUTH = "请授权这个应用程序以保存您的作品并共享。";
Blockly.Msg.CHANGE_VALUE_TITLE = "更改值：";
Blockly.Msg.CHAT = "通过在此框输入与您的合作者沟通！";
Blockly.Msg.CLEAN_UP = "清理块";
Blockly.Msg.COLLAPSE_ALL = "折叠块";
Blockly.Msg.COLLAPSE_BLOCK = "折叠块";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "颜色1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "颜色2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "用一个给定的比率(0.0-1.0)混合两种颜色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/颜色";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "从调色板中选择一种颜色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "随机颜色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "随机选择一种颜色。";
Blockly.Msg.COLOUR_RGB_BLUE = "蓝色";
Blockly.Msg.COLOUR_RGB_GREEN = "绿色";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "红色";
Blockly.Msg.COLOUR_RGB_TITLE = "颜色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "通过指定红色、绿色和蓝色的量创建一种颜色。所有的值必须介于0和100之间。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "中断循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "继续下一次循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "中断包含它的循环。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳过这个循环的剩余部分，并继续下一次迭代。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告：此块仅可用于在一个循环内。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "为每个项目 %1 在列表中 %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍历每个列表中的项目，将变量“%1”设定到该项中，然后执行某些语句。";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "使用 %1 从范围 %2 到 %3 每隔 %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "从起始数到结尾数中取出变量“%1”的值，按指定的时间间隔，执行指定的块。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "在if语句块中增加一个条件。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "添加一个最终的，包括所有情况的节到if块中。";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "增加、删除或重新排列各节来重新配置“if”块。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否则";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否则如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "如果值为真，执行一些语句。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "如果值为真，则执行语句的第一块。否则，则执行语句的第二块。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一个值为真，则执行语句的第一个块。否则，如果第二个值为真，则执行语句的第二块。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一个值为真，则执行语句的第一块。否则，如果第二个值为真，则执行语句的第二块。如果没有值为真，则执行语句的最后一块。";
Blockly.Msg.CONTROLS_REPEAT_FOREVER = "不斷重複";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For循环";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "执行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重复 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次执行一些语句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重复直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重复当";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "只要值为假，执行一些语句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "只要值为真，执行一些语句。";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_RECORD_ID = "編號ID";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_SERVICE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_SERVICE_TITLE = "AOP上傳資料設定(JSON)";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_SERVICE_TOOLTIP = "AOP Upload Data Set";  // untranslated
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_VALUE_FIELD_1 = "資料1";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_VALUE_FIELD_2 = "資料2";
Blockly.Msg.CPFAOP_CONTENT_UPLOAD_VALUE_FIELD_3 = "資料3";
Blockly.Msg.CPFAOP_DELAY_TIME_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.CPFAOP_DELAY_TIME_SET = "時間(ms)";
Blockly.Msg.CPFAOP_DELAY_TIME_TITLE = "CPF延遲";
Blockly.Msg.CPFAOP_DELAY_TIME_TOOLTIP = "CPF 延遲時間";
Blockly.Msg.CPFAOP_JSONDATA_DOWNLOAD_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.CPFAOP_JSONDATA_DOWNLOAD_RECORD_ID = "編號(ID)";
Blockly.Msg.CPFAOP_JSONDATA_DOWNLOAD_TITLE = "AOP資料下載";
Blockly.Msg.CPFAOP_JSONDATA_DOWNLOAD_TOOLTIP = "AOP資料下載(JSON)";
Blockly.Msg.CPFAOP_JSONDATA_PARSE_FROM = " 從 ";
Blockly.Msg.CPFAOP_JSONDATA_PARSE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.CPFAOP_JSONDATA_PARSE_TITLE = "雲端資料(JSON)";
Blockly.Msg.CPFAOP_JSONDATA_PARSE_TOOLTIP = "取出JSON格式資料";
Blockly.Msg.CPFAOP_JSONDATA_PARSE_VALUE_ID = " 取出";
Blockly.Msg.CPFAOP_JSONDATA_UPLOAD_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.CPFAOP_JSONDATA_UPLOAD_RECORD_ID = "編號(ID)";
Blockly.Msg.CPFAOP_JSONDATA_UPLOAD_TITLE = "AOP資料上傳";
Blockly.Msg.CPFAOP_JSONDATA_UPLOAD_TOOLTIP = "AOP資料上傳";
Blockly.Msg.CPFAOP_JSONDATA_UPLOAD_VALUE = "資料(JSON)";
Blockly.Msg.CPF_CONTROL_REPEAT = "設定 CPF 重複執行程式";
Blockly.Msg.CPF_EXTEN_ADXL345_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_ADXL345_SCL = "SCL Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_ADXL345_SDA = "SDA Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_ADXL345_TITLE = "(ADXL345)3-Axis Accelerometer";  // untranslated
Blockly.Msg.CPF_EXTEN_ADXL345_TOOLTIP = "(ADXL345)3-Axis Accelerometer return and setting";  // untranslated
Blockly.Msg.CPF_EXTEN_ADXL345_XYZ = "Get XYZ value";  // untranslated
Blockly.Msg.CPF_EXTEN_BLUE_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_BLUE_LED_TITLE = "Blue Led ";  // untranslated
Blockly.Msg.CPF_EXTEN_BLUE_LED_TOOLTIP = "Turn the blue led on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_COILLATCH_RELAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_COILLATCH_RELAY_TITLE = "2 Coil Latching Relay ";  // untranslated
Blockly.Msg.CPF_EXTEN_COILLATCH_RELAY_TOOLTIP = "This module is based on 2-Coil Latching Relay";  // untranslated
Blockly.Msg.CPF_EXTEN_COLOR_FLASH_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_COLOR_FLASH_LED_TITLE = "Color Flash LED ";  // untranslated
Blockly.Msg.CPF_EXTEN_COLOR_FLASH_LED_TOOLTIP = "Enable/Disable Color Flash LED";  // untranslated
Blockly.Msg.CPF_EXTEN_DRY_REED_RELAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_DRY_REED_RELAY_TITLE = "Dry-Reed Relay ";  // untranslated
Blockly.Msg.CPF_EXTEN_DRY_REED_RELAY_TOOLTIP = "It is a relay module which works through magnetizing the vibration reed via the current in the coils";  // untranslated
Blockly.Msg.CPF_EXTEN_DS18B20_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_DS18B20_TITLE = "(DS18B20) Water Temperature Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_DS18B20_TOOLTIP = "Get the status of water temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_ELECTRO_MAGNET_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_ELECTRO_MAGNET_TITLE = "Electromagnet ";  // untranslated
Blockly.Msg.CPF_EXTEN_ELECTRO_MAGNET_TOOLTIP = "The magnetic field of all the turns of wire passes through the center of the coil, creating a strong magnetic field there";  // untranslated
Blockly.Msg.CPF_EXTEN_GET_VALUE = "Get Value";  // untranslated
Blockly.Msg.CPF_EXTEN_GREEN_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_GREEN_LED_TITLE = "Green Led ";  // untranslated
Blockly.Msg.CPF_EXTEN_GREEN_LED_TOOLTIP = "Turn the green led on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_BACKLIGHT_BLUE = "Blue";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_BACKLIGHT_GREEN = "Green";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_BACKLIGHT_RED = "Red";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_CLEAR_TITLE = "Clear";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_CLEAR_TOOLTIP = "Clears the LCD screen and positions the cursor in the upper-left corner.";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_DISPLAY = "Set Display ";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_DISPLAY_OFF = "Off";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_DISPLAY_ON = "On";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_DISPLAY_TOOLTIP = "Enable/Disable the RGB LCD";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_PRINT_TITLE = "Print";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_PRINT_TOOLTIP = "Prints text to the LCD.";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SETCURSOR_COL = "COL.";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SETCURSOR_ROW = "ROW";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SETCURSOR_TITLE = "setCursor";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SETCURSOR_TOOLTIP = "Position the LCD cursor.";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SET_BACKLIGHT_TITLE = "LCD Backlight";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_SET_BACKLIGHT_TOOLTIP = "Set Backlight color.";  // untranslated
Blockly.Msg.CPF_EXTEN_I2CLCD_TITLE = "RGB LCD(I2C)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ALCOHOL_GET_VALUE = "Get Value";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ALCOHOL_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ALCOHOL_PIN = "Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ALCOHOL_TITLE = "Alcohol Sensor(A)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ALCOHOL_TOOLTIP = "Get value of alcohol sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_BUTTON_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_BUTTON_TITLE = "Button";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_BUTTON_TOOLTIP = "Get the button status";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_CO2_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_CO2_PPM = "CO2";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_CO2_TEMPERATURE = "Temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_CO2_TITLE = "CO2 Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_CO2_TOOLTIP = "Get the status of CO2 or temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_COLLISION_SENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_COLLISION_SENSOR_TITLE = "Collision Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_COLLISION_SENSOR_TOOLTIP = "Get the status of Collision Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ELECSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ELECSENSOR_TITLE = "Electricity Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ELECSENSOR_TOOLTIP = "Get the status of Electricity Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_EMG_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_EMG_TITLE = "Muscle EMG Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_EMG_TOOLTIP = "Get the status of Muscle EMG Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_FLAMESENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_FLAMESENSOR_TITLE = "Flame Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_FLAMESENSOR_TOOLTIP = "Get the status of Flame Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_HCHO_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_HCHO_TITLE = "VOC Gas Sensor(HCHO)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_HCHO_TOOLTIP = "Get value of VOC gas sensor(HCHO)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_IRTEMPERATURE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_IRTEMPERATURE_TITLE = "Infrared Temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_IRTEMPERATURE_TOOLTIP = "Get the status of Infrared Temperature Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_JOYSTICK_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_JOYSTICK_TOOLTIP = "Get the status of Joystick";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_JOYSTICK_X_TITLE = "Joystick direction-X";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_JOYSTICK_Y_TITLE = "Joystick direction-Y";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LIGHTSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LIGHTSENSOR_TITLE = "Light Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LIGHTSENSOR_TOOLTIP = "Get the status of Light Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LINEFINDER_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LINEFINDER_TITLE = "Line Finder";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LINEFINDER_TOOLTIP = "Get the status of Line Finder Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LOUDNESS_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LOUDNESS_TITLE = "Loudness Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LOUDNESS_TOOLTIP = "Get the status of Loudness Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LUMINANACE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LUMINANACE_TITLE = "Luminanace Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_LUMINANACE_TOOLTIP = "Get the status of Luminanace Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MAGNETIC_SWITCH_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MAGNETIC_SWITCH_TITLE = "Magnetic Switch";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MAGNETIC_SWITCH_TOOLTIP = "Get the status of magnetic switch";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MOISTURE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MOISTURE_TITLE = "Moisture Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MOISTURE_TOOLTIP = "Get the status of Moisture Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ2_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ2_TITLE = "Combustible Gas Sensor(MQ2)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ2_TOOLTIP = "Get value of combustible gas sensor(MQ2)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ3_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ3_TITLE = "Alcohol Sensor(MQ3)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ3_TOOLTIP = "Get value of alcohol sensor(MQ3)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ5_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ5_TITLE = "Natural Gas Sensor(MQ5)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ5_TOOLTIP = "Get value of natural gas sensor(MQ5)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ9_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ9_TITLE = "Carbon Monoxide Sensor(MQ9)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_MQ9_TOOLTIP = "Get value of carbon monoxide sensor(MQ9)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_O2_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_O2_TITLE = "Oxygen Sensor(O2)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_O2_TOOLTIP = "Get value of oxygen sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PIR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PIR_TITLE = "PIR Motion Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PIR_TOOLTIP = "Get the status of PIR Motion Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PM25_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PM25_TITLE = "Dust Sensor(PM2.5)";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_PM25_TOOLTIP = "Get the status of dust sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ROTARY_VR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ROTARY_VR_TITLE = "Rotary Angle Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_ROTARY_VR_TOOLTIP = "Get the status of rotary angle sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SHARPIR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SHARPIR_TITLE = "Sharp IR Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SHARPIR_TOOLTIP = "Get the status of Sharp IR Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SKINGSR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SKINGSR_TITLE = "Skin GSR Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SKINGSR_TOOLTIP = "Get the status of Skin GSR Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SLIDE_VR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SLIDE_VR_TITLE = "Slide Potentiometer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SLIDE_VR_TOOLTIP = "Get the status of slide potentiometer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SOUNDSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SOUNDSENSOR_TITLE = "Sound Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SOUNDSENSOR_TOOLTIP = "Get the status of Sound Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SWITCH_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SWITCH_TITLE = "Slide Switch";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_SWITCH_TOOLTIP = "Get the switch status";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TEMPSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TEMPSENSOR_TITLE = "Temperature Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TEMPSENSOR_TOOLTIP = "Get the status of Temperature Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TILT_SWITCH_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TILT_SWITCH_TITLE = "Tilt Switch";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TILT_SWITCH_TOOLTIP = "Get the status of tilt switch";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TOUCH_SENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TOUCH_SENSOR_TITLE = "Touch Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_TOUCH_SENSOR_TOOLTIP = "Get the status of touch sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_UVSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_UVSENSOR_TITLE = "UV Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_UVSENSOR_TOOLTIP = "Get the status of UV Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VIBRATION_SENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VIBRATION_SENSOR_TITLE = "Piezo Vibration Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VIBRATION_SENSOR_TOOLTIP = "Get the status of Piezo Vibration Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VOLTAGEDIV_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VOLTAGEDIV_TITLE = "Voltage Divider";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_VOLTAGEDIV_TOOLTIP = "Get the status of Voltage Divider";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_WATERSENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_WATERSENSOR_TITLE = "Water Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_IN_WATERSENSOR_TOOLTIP = "Get the status of Water Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_CLK = "CLK Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_DIO = "DIO Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_SET_LEVEL = "Level(0~10)";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_TITLE = "LED Bar";  // untranslated
Blockly.Msg.CPF_EXTEN_LEDBAR_TOOLTIP = "LED Bar level setting";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRING_LIGHT_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRING_LIGHT_TITLE = "LED String Light ";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRING_LIGHT_TOOLTIP = "Turn string light on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRIP_DRIVER_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRIP_DRIVER_TITLE = "LED Strip Driver ";  // untranslated
Blockly.Msg.CPF_EXTEN_LED_STRIP_DRIVER_TOOLTIP = "Turn LED Strip on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_MINI_FAN_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_MINI_FAN_TITLE = "Mini Fan ";  // untranslated
Blockly.Msg.CPF_EXTEN_MINI_FAN_TOOLTIP = "Enable/Disable Mini Fan";  // untranslated
Blockly.Msg.CPF_EXTEN_MOSFET_RELAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_MOSFET_RELAY_TITLE = "MOSFET Relay ";  // untranslated
Blockly.Msg.CPF_EXTEN_MOSFET_RELAY_TOOLTIP = "MOSFET enables you to control higher voltage";  // untranslated
Blockly.Msg.CPF_EXTEN_PIN = "Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_PIN1 = "Pin1#";  // untranslated
Blockly.Msg.CPF_EXTEN_PIN2 = "Pin2#";  // untranslated
Blockly.Msg.CPF_EXTEN_PURPLE_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_PURPLE_LED_TITLE = "Purple Led ";  // untranslated
Blockly.Msg.CPF_EXTEN_PURPLE_LED_TOOLTIP = "Turn the purple led on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_PLAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_PLAY_TITLE = "Recorder:Play ";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_PLAY_TOOLTIP = "Recorder play";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_RECORDING_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_RECORDING_TITLE = "Recorder:Recording ";  // untranslated
Blockly.Msg.CPF_EXTEN_RECORDER_RECORDING_TOOLTIP = "Voice recording";  // untranslated
Blockly.Msg.CPF_EXTEN_RED_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_RED_LED_TITLE = "Red Led";  // untranslated
Blockly.Msg.CPF_EXTEN_RED_LED_TOOLTIP = "Turn the red led on/off.";  // untranslated
Blockly.Msg.CPF_EXTEN_RELAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_RELAY_TITLE = "Relay ";  // untranslated
Blockly.Msg.CPF_EXTEN_RELAY_TOOLTIP = " When set to HIGH, the LED will light up and the relay will close allowing current to flow.";  // untranslated
Blockly.Msg.CPF_EXTEN_RGB_COLOR_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_RGB_COLOR_LED_TITLE = "RGB COLOR LED ";  // untranslated
Blockly.Msg.CPF_EXTEN_RGB_COLOR_LED_TOOLTIP = "Turn RGB COLOR LED on/off";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_DATATYPE = "Data Type";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_HUMI = "Humidity";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_SETTING_PIN = "Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_TEMP = "Temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_TITLE = "DHT11";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT11_TOOLTIP = "get temperature and humidity data";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_DATATYPE = "Data Type";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_HUMI = "Humidity";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_SETTING_PIN = "Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_TEMP = "Temperature";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_TITLE = "DHT22";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_DHT22_TOOLTIP = "get temperature and humidity data";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_B = "Blue";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_COLORTEMP = "Color Temperatures";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_COMP = "data";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_DATATYPE = "Read object";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_G = "Green";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_R = "Red";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_TITLE = "RGB Color Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_SENSOR_TCS34725_TOOLTIP = "get RGB & color temperatures";  // untranslated
Blockly.Msg.CPF_EXTEN_SERVO_DEGREE = "degree ";  // untranslated
Blockly.Msg.CPF_EXTEN_SERVO_DELAYTIME = "delay time(ms)) ";  // untranslated
Blockly.Msg.CPF_EXTEN_SERVO_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_SERVO_TITLE = "Servo ";  // untranslated
Blockly.Msg.CPF_EXTEN_SERVO_TOOLTIP = "Moves servo to degree 0~180";  // untranslated
Blockly.Msg.CPF_EXTEN_SPDT_RELAY_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_SPDT_RELAY_TITLE = "SPDT Relay ";  // untranslated
Blockly.Msg.CPF_EXTEN_SPDT_RELAY_TOOLTIP = "Single Pole Double Throw Relay(SPDT)";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_BRIGHTNESS_DARKEST = "BRIGHT_DARKEST";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_BRIGHTNESS_SET = "LED Brightness Setting";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_BRIGHTNESS_TYPICAL = "BRIGHT_TYPICAL";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_CLEAR_TITLE = "Clear Dispaly";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_CLEAR_TOOLTIP = "Clears the Display screen.";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_DISPLAY_DATA_TITLE = "4-Digit Display";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_PIN_CLK = "Clk Pin";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_PIN_DATA = "Data Pin";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_TITLE = "4-Digit Display";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637LED_TOOLTIP = "Prints number to the display.";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637_DIGIT_1 = "Digital 1";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637_DIGIT_2 = "Digital 2";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637_DIGIT_3 = "Digital 3";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637_DIGIT_4 = "Digital 4";  // untranslated
Blockly.Msg.CPF_EXTEN_TM1637_POINT = "Point";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_DISTANCE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_DISTANCE_TITLE = "Ultrasonic Disrance";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_DISTANCE_TOOLTIP = "Ultrasonic distance return and setting";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_SETTING_ECHO = "Echo Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_SETTING_TITLE = "Ultrasonic(HC-SR04) Sensor";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_SETTING_TOOLTIP = "Ultrasonic(HC-SR04)Pin Setting.";  // untranslated
Blockly.Msg.CPF_EXTEN_ULTRASONIC_SETTING_TRIG = "Trig Pin#";  // untranslated
Blockly.Msg.CPF_EXTEN_VIBRATION_MOTOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_EXTEN_VIBRATION_MOTOR_TITLE = "Vibration Motor ";  // untranslated
Blockly.Msg.CPF_EXTEN_VIBRATION_MOTOR_TOOLTIP = "Enable/Disable Vibration Motor ";  // untranslated
Blockly.Msg.CPF_EXTEN_WRITE_VALUE = "Write Value";  // untranslated
Blockly.Msg.CPF_INOUT_UI_GET_VALUE = "Get control panel value";  // untranslated
Blockly.Msg.CPF_INOUT_UI_SET_VALUE = "Set control panel value";  // untranslated
Blockly.Msg.CPF_NO_TONE_PIN = "no tone/voice Pin#";  // untranslated
Blockly.Msg.CPF_TONE_APPENDTEXT_DURATION = "duration";  // untranslated
Blockly.Msg.CPF_TONE_APPENDTEXT_FREQ = "frequency";  // untranslated
Blockly.Msg.CPF_TONE_APPENDTEXT_PIN = "Tone/speaker Pin#";  // untranslated
Blockly.Msg.CPF_TONE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";  // untranslated
Blockly.Msg.CPF_TONE_TITLE = "Tone";  // untranslated
Blockly.Msg.CPF_TONE_TOOLTIP = "The pin can be connected to buzzer/speaker to play tone";  // untranslated
Blockly.Msg.DELETE_ALL_BLOCKS = "删除所有%1块吗？";
Blockly.Msg.DELETE_BLOCK = "删除块";
Blockly.Msg.DELETE_BLOCKS_LOAD_LESSON = "確定刪除所有積木且重設回課程?";
Blockly.Msg.DELETE_X_BLOCKS = "删除 %1 块";
Blockly.Msg.DISABLE_BLOCK = "禁用块";
Blockly.Msg.DUPLICATE_BLOCK = "复制";
Blockly.Msg.ENABLE_BLOCK = "启用块";
Blockly.Msg.EXPAND_ALL = "展开块";
Blockly.Msg.EXPAND_BLOCK = "展开块";
Blockly.Msg.EXTERNAL_INPUTS = "外部输入";
Blockly.Msg.HELP = "帮助";
Blockly.Msg.INLINE_INPUTS = "单行输入";
Blockly.Msg.INOUT_ANALOG_READ = "Reads analog data; Return value between 0 and 1024";  // untranslated
Blockly.Msg.INOUT_ANA_READ = "AnalogRead PIN#";  // untranslated
Blockly.Msg.INOUT_ANA_WRITE = "Analog Write";  // untranslated
Blockly.Msg.INOUT_BUI_LED = "Integrated LED Stat";  // untranslated
Blockly.Msg.INOUT_DIGITAL_READ = "Reads the value from a specified digital pin, either HIGH or LOW";  // untranslated
Blockly.Msg.INOUT_DIG_READ = "Digital read PIN#";  // untranslated
Blockly.Msg.INOUT_HIGH_LEVEL = "HIGH";  // untranslated
Blockly.Msg.INOUT_LOW_LEVEL = "LOW";  // untranslated
Blockly.Msg.INOUT_STAT = "STAT";  // untranslated
Blockly.Msg.INOUT_VALUE = "Value";  // untranslated
Blockly.Msg.INPOUT_DIGITAL_WRITE = "DigitalWrite PIN#";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "创建空列表";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一个列表，长度为 0，不包含任何数据记录";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "列表";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "增加、删除或重新排列各部分以此重新配置这个列表块。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "建立字串使用";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "将一个项添加到列表中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一个具有任意数量项目的列表。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒数第#";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "获得";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出并移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最后";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "随机";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "空白";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的项。#1是第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "随机返回列表中的一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除并返回列表中的第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除并返回列表中的指定位置的项。#1 是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除并返回列表中的指定位置的项。#1 是第一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除并返回列表中的最后一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除并返回列表中的一个随机项目中。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一项";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "删除在列表中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的项。#1 是第一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最后一项";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "删除列表中的一个随机的项。";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到倒数第#";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到#";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到最后";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "从头获得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "从倒数#取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "从#取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "空白";
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "复制列表中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出第一个项出现";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出最后一个项出现";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一/最后一个匹配项的索引值。如果找不到项目则返回0。";
Blockly.Msg.LISTS_INLIST = "在列表中";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1是空的";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "如果改列表为空，则返回真。";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "%1的长度";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的长度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用项 %1 重复 %2 次";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重复次数的值的列表。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "为";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
Blockly.Msg.LISTS_SET_INDEX_SET = "设置";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始处添加该项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中指定位置的项。#1是第一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "将该项追加到列表的末尾。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中随机插入项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "设置列表中的第一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "设置在列表中指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "设置在列表中指定位置的项。#1是第一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "设置列表中的最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "设置列表中一个随机的项目。";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "升序";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "降序";
Blockly.Msg.LISTS_SORT_TITLE = "排序%1 %2 %3";
Blockly.Msg.LISTS_SORT_TOOLTIP = "排序一个列表的拷贝。";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "按字母排序，忽略大小写";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "按数字排序";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "按字母排序";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "从文本制作列表";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "从列表拆出文本";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "加入文本列表至一个文本，由分隔符分隔。";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "拆分文本到文本列表，按每个分隔符拆分。";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "用分隔符";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "假";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回真或假。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果两个输入结果相等，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一个输入结果比第二个大，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一个输入结果大于或等于第二个输入结果，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一个输入结果比第二个小，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一个输入结果小于或等于第二个输入结果，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果两个输入结果不相等，则返回真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "非%1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果输入结果为假，则返回真；如果输入结果为真，则返回假。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回空值。";
Blockly.Msg.LOGIC_OPERATION_AND = "和";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果两个输入结果都为真，则返回真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少有一个输入结果为真，则返回真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "测试";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/条件运算符";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果为假";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果为真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "检查“test”中的条件。如果条件为真，则返回“if true”的值，否则，则返回“if false”的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://zh.wikipedia.org/wiki/算术";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回两个数字的和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回两个数字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回两个数字的区别。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回两个数字的乘积。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第一个数的第二个数次幂。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/%E5%8A%A0%E6%B3%95";
Blockly.Msg.MATH_CHANGE_TITLE = "更改 %1 由 %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "将一个数添加到变量“%1”。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/数学常数";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一个常见常量：π (3.141......)，e (2.718...)、φ (1.618...)、 sqrt(2) (1.414......)、sqrt(½) (0.707......)或 ∞（无穷大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制数字 %1 介于 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制数字介于两个指定的数字之间";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶数";
Blockly.Msg.MATH_IS_NEGATIVE = "为负";
Blockly.Msg.MATH_IS_ODD = "是奇数";
Blockly.Msg.MATH_IS_POSITIVE = "为正";
Blockly.Msg.MATH_IS_PRIME = "是质数";
Blockly.Msg.MATH_IS_TOOLTIP = "如果数字是偶数、奇数、非负整数、正数、负数或如果它可被某数字整除，则返回真或假。";
Blockly.Msg.MATH_IS_WHOLE = "为整数";
Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg.MATH_MODULO_TITLE = "取余数自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "返回这两个数字相除后的余数。";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/数";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一个数字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "列表中的平均数";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "列表中的最大值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "列表中位数";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "列表中的最小值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "列表模式";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "列表的随机项";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "列表中的标准差";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "列表中的数的总和";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中的数值的平均值。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中最大数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中的中位数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中最小数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回列表中的最常见的项的列表。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "从列表中返回一个随机的元素。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表的标准偏差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有数字的和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "随机分数";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介于（包含）0.0到1.0之间的随机数。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "从 %1 到 %2 之间的随机整数";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "返回两个指定的范围（含）之间的随机整数。";
Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/数值修约";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "向上舍入";
Blockly.Msg.MATH_ROUND_TOOLTIP = "数字向上或向下舍入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "绝对";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "平方根";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回一个数的绝对值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回数的e次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回一个数的自然对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回数字的对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回数的逻辑非。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回数的10次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回数的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函数";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回一个数的反余弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回一个数的反正弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的余弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.ME = "我";
Blockly.Msg.MOTODUINO_CPFAOP_CONTENT_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPFAOP_CONTENT_UI_SET = "畫面顯示";
Blockly.Msg.MOTODUINO_CPFAOP_CONTENT_UI_TITLE = "主題內容";
Blockly.Msg.MOTODUINO_CPFAOP_CONTENT_UI_TOOLTIP = "設定主題內容";
Blockly.Msg.MOTODUINO_CPFAOP_DATE_GET = "取得目前時間";
Blockly.Msg.MOTODUINO_CPFAOP_DATE_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPFAOP_DATE_TITLE = "";
Blockly.Msg.MOTODUINO_CPFAOP_DATE_TOOLTIP = "取得目前時間";
Blockly.Msg.MOTODUINO_CPF_FAN_CONTROL_GET_VALUE = "取得轉速";
Blockly.Msg.MOTODUINO_CPF_FAN_CONTROL_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_FAN_CONTROL_SET_VALUE = "設定轉速";
Blockly.Msg.MOTODUINO_CPF_FAN_CONTROL_TITLE = "風扇";
Blockly.Msg.MOTODUINO_CPF_FAN_CONTROL_TOOLTIP = "風扇轉速控制";
Blockly.Msg.MOTODUINO_CPF_FAN_LEVEL_HIGH = "高速";
Blockly.Msg.MOTODUINO_CPF_FAN_LEVEL_MID = "中速";
Blockly.Msg.MOTODUINO_CPF_FAN_LEVEL_SLOW = "慢速";
Blockly.Msg.MOTODUINO_CPF_FAN_LEVEL_STOP = "停止";
Blockly.Msg.MOTODUINO_CPF_FAN_UI_GET_VALUE = "取得設定值";
Blockly.Msg.MOTODUINO_CPF_FAN_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_FAN_UI_TITLE = "風扇";
Blockly.Msg.MOTODUINO_CPF_FAN_UI_TOOLTIP = "取得風扇轉速";
Blockly.Msg.MOTODUINO_CPF_LED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_LED_SET_OFF = "OFF";
Blockly.Msg.MOTODUINO_CPF_LED_SET_ON = "ON";
Blockly.Msg.MOTODUINO_CPF_LED_SET_VALUE = "設定 ";
Blockly.Msg.MOTODUINO_CPF_LED_TITLE = "白光LED";
Blockly.Msg.MOTODUINO_CPF_LED_TOOLTIP = "白光LED控制";
Blockly.Msg.MOTODUINO_CPF_LIGHT_SENSOR_GET_VALUE = "取得數值";
Blockly.Msg.MOTODUINO_CPF_LIGHT_SENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_LIGHT_SENSOR_TITLE = "光感測";
Blockly.Msg.MOTODUINO_CPF_LIGHT_SENSOR_TOOLTIP = "取得光感測元件數值";
Blockly.Msg.MOTODUINO_CPF_LIGHT_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_LIGHT_UI_SET = "畫面顯示";
Blockly.Msg.MOTODUINO_CPF_LIGHT_UI_TITLE = "光感測";
Blockly.Msg.MOTODUINO_CPF_LIGHT_UI_TOOLTIP = "設定畫面環境光值";
Blockly.Msg.MOTODUINO_CPF_RGBLED_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_RGBLED_TITLE = "彩色LED";
Blockly.Msg.MOTODUINO_CPF_RGBLED_TOOLTIP = "RGB LED顏色設定";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_GET_VALUE = "取得設定值";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_GET_VALUE_B = "藍色";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_GET_VALUE_G = "綠色";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_GET_VALUE_R = "紅色";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_TITLE = "彩色LED";
Blockly.Msg.MOTODUINO_CPF_RGBLED_UI_TOOLTIP = "取得 RGB-Led 亮度值";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_SENSOR_GET_VALUE = "取得數值(C)";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_SENSOR_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_SENSOR_TITLE = "溫度裝置";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_SENSOR_TOOLTIP = "取得溫度感測元件數值";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_UI_SET = "畫面顯示";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_UI_TITLE = "溫度";
Blockly.Msg.MOTODUINO_CPF_TEMPERATURE_UI_TOOLTIP = "設定畫面溫度值";
Blockly.Msg.MOTODUINO_CPF_TITLE_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_TITLE_UI_SET = "畫面顯示";
Blockly.Msg.MOTODUINO_CPF_TITLE_UI_SET_TOOLTIP = "設定主題名稱";
Blockly.Msg.MOTODUINO_CPF_TITLE_UI_TITLE = "主題名稱";
Blockly.Msg.MOTODUINO_CPF_WHITELED_UI_GET_VALUE = "取得設定值";
Blockly.Msg.MOTODUINO_CPF_WHITELED_UI_HELPURL = "http://www.acer.com/ac/zh/TW/content/byoc-consumer";
Blockly.Msg.MOTODUINO_CPF_WHITELED_UI_TITLE = "白光LED";
Blockly.Msg.MOTODUINO_CPF_WHITELED_UI_TOOLTIP = "取得白光LED亮度";
Blockly.Msg.NEW_VARIABLE = "新变量...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新变量的名称：";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "空白";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "允许声明";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "与：";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "运行用户定义的函数“%1”。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "运行用户定义的函数“%1”，并使用它的输出值。";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "与：";
Blockly.Msg.PROCEDURES_CREATE_DO = "创建“%1”";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "描述该功能...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "空白";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "做点什么";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "至";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "创建一个不带输出值的函数。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "返回";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "创建一个有输出值的函数。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函数具有重复参数。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "突出显示函数定义";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值为真，则返回第二个值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 仅在定义函数内可使用此块。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "输入名称：";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "添加函数输入。";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "输入";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "添加、删除或重新排此函数的输入。";
Blockly.Msg.REDO = "重做";
Blockly.Msg.REMOVE_COMMENT = "删除注释";
Blockly.Msg.RENAME_VARIABLE = "重命名变量...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "将所有“%1”变量重命名为:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "追加文本";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "将一些文本追加到变量“%1”。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "为小写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "为首字母大写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "为大写";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小写复制这段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST = "获得第一个字符";
Blockly.Msg.TEXT_CHARAT_FROM_END = "获得倒数第#个字符";
Blockly.Msg.TEXT_CHARAT_FROM_START = "获得字符#";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "于文本中";
Blockly.Msg.TEXT_CHARAT_LAST = "获得最后一个字符";
Blockly.Msg.TEXT_CHARAT_RANDOM = "获取随机的字母";
Blockly.Msg.TEXT_CHARAT_TAIL = "空白";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位于指定位置的字母。";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "将一个项添加到文本中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、移除或重新排列各节来重新配置这个文本块。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到倒数第#个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到字符#";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到最后一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自文本";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串自第一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自#到末尾";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自#";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "空白";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文本。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "自文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "寻找第一个出现的文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "寻找最后一个出现的文本";
Blockly.Msg.TEXT_INDEXOF_TAIL = "空白";
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二个字串中的第一/最后一个匹配项的索引值。如果未找到则返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1是空的";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的文本为空，则返回真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通过串起任意数量的项以建立一段文字。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "%1的长度";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回提供文本的字母数（包括空格）。";
Blockly.Msg.TEXT_NEWLINE_TEXT = "字串";
Blockly.Msg.TEXT_NEWLINE_TITLE = "字串 換行";
Blockly.Msg.TEXT_NEWLINE_TOOLTIP = "新一行字串 ";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "打印%1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "打印指定的文字、数字或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "提示用户输入数字。";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "提示用户输入一些文本。";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "输入数字并显示提示消息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "输入数字并显示提示消息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字符串";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "一个字母、单词或一行文本。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除两侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右侧空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "复制这段文字的同时删除两端多余的空格。";
Blockly.Msg.TODAY = "今天";
Blockly.Msg.UNDO = "撤销";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "项目";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "创建“设定%1”";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此变量的值。";
Blockly.Msg.VARIABLES_SET = "赋值 %1 到 %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "创建“获得%1”";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "设置此变量，以使它和输入值相等。";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;