
/*
    CPF Arduino Lesson 1~7  
    Author: Motoduino  2016/7/25
*/

'use strict';

var CPFArduino = {};

/**
 * Lesson examples
 */
CPFArduino.Lesson1 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="cpf_title_ui_set" id="qOsR;#5+t(%yCfDL88kq" x="38" y="38">',
	'    <value name="VALUE">',
	'      <block type="text" id="`.#WMNLnwi9nrX{Z~hT8">',
	'        <field name="TEXT">Manual Mode</field>',
	'      </block>',
	'    </value>',
	'    <next>',
	'      <block type="controls_if" id="axFPI:s^*?P]jXRfCQwn">',
	'        <mutation else="1"></mutation>',
	'        <value name="IF0">',
	'          <block type="logic_compare" id="~RWOZizC6T1s^|AT1.Y(">',
	'            <field name="OP">LT</field>',
	'            <value name="A">',
	'              <block type="cpf_lightsensor_get" id="s(fEbh*r|i0D1Zdg/W{v"></block>',
	'            </value>',
	'            <value name="B">',
	'              <block type="math_number" id="{OvoLRpJ;S+S@d7KWFYX">',
	'                <field name="NUM">500</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <statement name="DO0">',
	'          <block type="cpf_rgbled_set_colour" id=",_V-Ez.zZ_N,y?_^^B(P">',
	'            <value name="LEDCOLOUR">',
	'              <block type="cpf_rgbled_ui_get" id="}ha_/|4tZY491CetfV^("></block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <statement name="ELSE">',
	'          <block type="cpf_rgbled_set_colour" id="JI!g=sG7=-LR5RsDrPG;">',
	'            <value name="LEDCOLOUR">',
	'              <block type="colour_picker" id="N0x8,4d[f_g4Fw`h#[t#">',
	'                <field name="COLOUR">#000000</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <next>',
	'          <block type="cpf_control_repeat" id="60f@)AOm]OGGht9.9VO7"></block>',
	'        </next>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson2 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="cpf_title_ui_set" id="9XqTRhdTfE/+U0!|a@FW" x="38" y="38">',
	'    <value name="VALUE">',
	'      <block type="text" id="(DbPw3nC^JE8Xa5Btk(/">',
	'        <field name="TEXT">Manual Mode</field>',
	'      </block>',
	'    </value>',
	'    <next>',
	'      <block type="cpf_led_manaul_set" id="+R8Ao(FDNqd09:]xdlEv">',
	'        <value name="VALUE">',
	'          <block type="cpf_whiteled_ui_get" id="K4U?*^_F~F.a~AZ]9@P5"></block>',
	'        </value>',
	'        <next>',
	'          <block type="controls_if" id="6Ahjp[!0Jt_G6O)Y|m+z">',
	'            <mutation else="1"></mutation>',
	'            <value name="IF0">',
	'              <block type="logic_compare" id="G`,xra/i(_h]2V,:KtEo">',
	'                <field name="OP">EQ</field>',
	'                <value name="A">',
	'                  <block type="cpf_whiteled_ui_get" id="Oo5~8MBzbWgt7fZU@/CB"></block>',
	'                </value>',
	'                <value name="B">',
	'                  <block type="cpf_led_onoff" id="^FRW:mq]BKc{):T?bZfj">',
	'                    <field name="BOOL">ON</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'            <statement name="DO0">',
	'              <block type="cpf_fan_set" id=",7AB0,J%yJU-ZHv?{YRN">',
	'                <value name="VALUE">',
	'                  <block type="cpf_fanspeed_ui_get" id="*Hkg51-S)^G@=GPe0g0]"></block>',
	'                </value>',
	'              </block>',
	'            </statement>',
	'            <statement name="ELSE">',
	'              <block type="cpf_fan_set" id="UqL7tsu{RshdwEUTj2Yo">',
	'                <value name="VALUE">',
	'                  <block type="math_number" id="rH]YF2^ED0q2Ou1?OWhd">',
	'                    <field name="NUM">0</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </statement>',
	'            <next>',
	'              <block type="cpf_control_repeat" id="#5ngfjdnvwOz5D;#jDVM"></block>',
	'            </next>',
	'          </block>',
	'        </next>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson3 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="cpf_title_ui_set" id="sG.k#vVyqC[P/Nh].sZ)" x="38" y="38">',
	'    <value name="VALUE">',
	'      <block type="text" id="}Ed@K^|BPZVH)m`#|D?Z">',
	'        <field name="TEXT">Auto Mode</field>',
	'      </block>',
	'    </value>',
	'    <next>',
	'      <block type="controls_if" id="1!HU`+c2?/B#w1tp=3H;">',
	'        <mutation elseif="2" else="1"></mutation>',
	'        <value name="IF0">',
	'          <block type="logic_compare" id="6rR.Xf[Ue4UexDaX.`:%">',
	'            <field name="OP">LTE</field>',
	'            <value name="A">',
	'              <block type="cpf_temperature_get" id="]`_2w[[d{*M}@I=k8.O]"></block>',
	'            </value>',
	'            <value name="B">',
	'              <block type="math_number" id="k`.yLImZb[0`pPnm3~LX">',
	'                <field name="NUM">28</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <statement name="DO0">',
	'          <block type="cpf_fan_set" id="/{dN+`z0u-2zX^HE+I6I">',
	'            <value name="VALUE">',
	'              <block type="math_number" id="xCg/~4N.lM(#08se8Y@L">',
	'                <field name="NUM">0</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <value name="IF1">',
	'          <block type="logic_operation" id="!cv{;FK`;g{Ya+BS@7Jd">',
	'            <field name="OP">AND</field>',
	'            <value name="A">',
	'              <block type="logic_compare" id="`N|qb!B!2bQwGE]Ct*/1">',
	'                <field name="OP">GT</field>',
	'                <value name="A">',
	'                  <block type="cpf_temperature_get" id="XxQ2NE)BW2N(2PG|`Lj0"></block>',
	'                </value>',
	'                <value name="B">',
	'                  <block type="math_number" id="M)z{qEeUzY((H^je(]sk">',
	'                    <field name="NUM">28</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'            <value name="B">',
	'              <block type="logic_compare" id="b|C,{+^rI+/k^CDEKHtY">',
	'                <field name="OP">LTE</field>',
	'                <value name="A">',
	'                  <block type="cpf_temperature_get" id="!^4E3[8US?ZrYq)UO%X3"></block>',
	'                </value>',
	'                <value name="B">',
	'                  <block type="math_number" id="yd/=P*-^Qpz_W|#9rEsW">',
	'                    <field name="NUM">31</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <statement name="DO1">',
	'          <block type="cpf_fan_set" id=",tk,H,L{+liXkSbX:(fH">',
	'            <value name="VALUE">',
	'              <block type="math_number" id="ji%:rk~y057Bs0#UXBnn">',
	'                <field name="NUM">60</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <value name="IF2">',
	'          <block type="logic_operation" id="@4q[91G?RxY?=QFJOBj@">',
	'            <field name="OP">AND</field>',
	'            <value name="A">',
	'              <block type="logic_compare" id="pm}lykJ(67!YY%oQtS!}">',
	'                <field name="OP">GT</field>',
	'                <value name="A">',
	'                  <block type="cpf_temperature_get" id="6ED]{A|B^nHxh.PgXT~m"></block>',
	'                </value>',
	'                <value name="B">',
	'                  <block type="math_number" id="/F08?sFU@83e/G/iD_fd">',
	'                    <field name="NUM">31</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'            <value name="B">',
	'              <block type="logic_compare" id="sN/P.R90unNY*V##n[F4">',
	'                <field name="OP">LTE</field>',
	'                <value name="A">',
	'                  <block type="cpf_temperature_get" id="ZR-sBX(,v*0,~aNV@uk;"></block>',
	'                </value>',
	'                <value name="B">',
	'                  <block type="math_number" id="+VMGM-}3.;w=;sEJ(qWZ">',
	'                    <field name="NUM">35</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <statement name="DO2">',
	'          <block type="cpf_fan_set" id="kW7eSLhCg1m?bUAeGqhG">',
	'            <value name="VALUE">',
	'              <block type="math_number" id="*EYKEjQzDd9HHox/CcuH">',
	'                <field name="NUM">130</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <statement name="ELSE">',
	'          <block type="cpf_fan_set" id="/FAem:DkaSizNeSOU#zr">',
	'            <value name="VALUE">',
	'              <block type="math_number" id="UEov_AS?:LtdTuo^t|M8">',
	'                <field name="NUM">255</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </statement>',
	'        <next>',
	'          <block type="cpf_control_repeat" id="c{zfuQf;D2?uA@1;%:(n"></block>',
	'        </next>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson4 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="cpf_led_manaul_set" id="+R8Ao(FDNqd09:]xdlEv" x="38" y="38">',
	'    <value name="VALUE">',
	'      <block type="cpf_whiteled_ui_get" id="K4U?*^_F~F.a~AZ]9@P5"></block>',
	'    </value>',
	'    <next>',
	'      <block type="controls_if" id="6Ahjp[!0Jt_G6O)Y|m+z">',
	'        <mutation else="1"></mutation>',
	'        <value name="IF0">',
	'          <block type="logic_compare" id="G`,xra/i(_h]2V,:KtEo">',
	'            <field name="OP">EQ</field>',
	'            <value name="A">',
	'              <block type="cpf_whiteled_ui_get" id="Oo5~8MBzbWgt7fZU@/CB"></block>',
	'            </value>',
	'            <value name="B">',
	'              <block type="math_number" id="2Te_[-rz/8KMptYm%;H7">',
	'                <field name="NUM">1</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <statement name="DO0">',
	'          <block type="cpf_title_ui_set" id="|ns!{,cbh]N9NL{Zyg3P">',
	'            <value name="VALUE">',
	'              <block type="text" id="}(m+Y-oUR@Nc0FvJl/#w">',
	'                <field name="TEXT">Auto Mode</field>',
	'              </block>',
	'            </value>',
	'            <next>',
	'              <block type="cpf_rgbled_set_colour" id="8zuHmNj|]Y3s,WL@0AiG">',
	'                <value name="LEDCOLOUR">',
	'                  <block type="colour_random" id="x[k3jFs[OxNr5bCphA:8"></block>',
	'                </value>',
	'                <next>',
	'                  <block type="cpf_fan_set" id=",7AB0,J%yJU-ZHv?{YRN">',
	'                    <value name="VALUE">',
	'                      <block type="math_round" id="-7[cVPW)qc-J-V`HH**o">',
	'                        <field name="OP">ROUND</field>',
	'                        <value name="NUM">',
	'                          <shadow type="math_number" id=":wS4%rUF`3qD{z}?265_">',
	'                            <field name="NUM">3.1</field>',
	'                          </shadow>',
	'                          <block type="math_arithmetic" id="{IV(%a*U.nhCwMqTG^Vm">',
	'                            <field name="OP">MINUS</field>',
	'                            <value name="A">',
	'                              <shadow type="math_number" id="ZW!dPN|@[%]Orj(pBo;{">',
	'                                <field name="NUM">220</field>',
	'                              </shadow>',
	'                            </value>',
	'                            <value name="B">',
	'                              <shadow type="math_number" id="Q!VI?0N)(x5*TEG(i+~w">',
	'                                <field name="NUM">1</field>',
	'                              </shadow>',
	'                              <block type="math_arithmetic" id="PDS-5J6~Y5!.K~},{Gca">',
	'                                <field name="OP">MULTIPLY</field>',
	'                                <value name="A">',
	'                                  <shadow type="math_number" id="Dy*=3K:oMjRa.wiA%k!*">',
	'                                    <field name="NUM">1</field>',
	'                                  </shadow>',
	'                                  <block type="cpf_lightsensor_get" id="e6jP;J*F^EEHMkdGZB+P"></block>',
	'                                </value>',
	'                                <value name="B">',
	'                                  <shadow type="math_number" id="CO+EIeesyOXs0fXJdmVd">',
	'                                    <field name="NUM">0.2</field>',
	'                                  </shadow>',
	'                                </value>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <next>',
	'                      <block type="cpf_delay_time" id="09lwKa_p}(odemd?CFX|">',
	'                        <value name="VALUE">',
	'                          <block type="math_number" id="tzOe;_w~bmITv!B]ibcw">',
	'                            <field name="NUM">2000</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </next>',
	'                  </block>',
	'                </next>',
	'              </block>',
	'            </next>',
	'          </block>',
	'        </statement>',
	'        <statement name="ELSE">',
	'          <block type="cpf_title_ui_set" id="9XqTRhdTfE/+U0!|a@FW">',
	'            <value name="VALUE">',
	'              <block type="text" id="(DbPw3nC^JE8Xa5Btk(/">',
	'                <field name="TEXT">Manual Mode</field>',
	'              </block>',
	'            </value>',
	'            <next>',
	'              <block type="cpf_rgbled_set_colour" id="6RA4066OdgNJNgmJtR8E">',
	'                <value name="LEDCOLOUR">',
	'                  <block type="cpf_rgbled_ui_get" id="hR_(*~}.@e*?/S.ZuW}i"></block>',
	'                </value>',
	'                <next>',
	'                  <block type="cpf_fan_set" id="UqL7tsu{RshdwEUTj2Yo">',
	'                    <value name="VALUE">',
	'                      <block type="cpf_fanspeed_ui_get" id="^B@*nmYB8_Fdh{M0Z}Dj"></block>',
	'                    </value>',
	'                  </block>',
	'                </next>',
	'              </block>',
	'            </next>',
	'          </block>',
	'        </statement>',
	'        <next>',
	'          <block type="cpf_control_repeat" id="NhrN/lBx2#,LsMSiEWQF"></block>',
	'        </next>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson5 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="controls_for" id="1BcSmo-3+bGYfD@QG)Ig" x="38" y="38">',
	'    <field name="VAR">index</field>',
	'    <value name="FROM">',
	'      <shadow type="math_number" id="*?Uk?-{XQ3rT?d@x+YU5">',
	'        <field name="NUM">1</field>',
	'      </shadow>',
	'    </value>',
	'    <value name="TO">',
	'      <shadow type="math_number" id="T{/FKz|oU[Zhsw[!g_y(">',
	'        <field name="NUM">10</field>',
	'      </shadow>',
	'    </value>',
	'    <value name="BY">',
	'      <shadow type="math_number" id="oNEWyG7yAcVbP:68r/-a">',
	'        <field name="NUM">1</field>',
	'      </shadow>',
	'    </value>',
	'    <statement name="DO">',
	'      <block type="variables_set" id="ZMZ?bFq}0a)le0L:b^qM">',
	'        <field name="VAR">celsius</field>',
	'        <value name="VALUE">',
	'          <block type="cpf_temperature_get" id="Sp+#8fAm%Is5i63Vh/DW"></block>',
	'        </value>',
	'        <next>',
	'          <block type="variables_set" id="c]|Km#A.C)a7NEJoWZkU">',
	'            <field name="VAR">date</field>',
	'            <value name="VALUE">',
	'              <block type="cpfaop_date_get" id="DNU[JSPy~K@8{dL?Vk[("></block>',
	'            </value>',
	'            <next>',
	'              <block type="controls_if" id="rxI-PQV+c_AR*RE:2nT~">',
	'                <mutation else="1"></mutation>',
	'                <value name="IF0">',
	'                  <block type="logic_compare" id="bxIB@QGd7IDj#}.`A[EF">',
	'                    <field name="OP">GT</field>',
	'                    <value name="A">',
	'                      <block type="variables_get" id="C7/^;0W@Q1IA~]jpmDDv">',
	'                        <field name="VAR">celsius</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="B">',
	'                      <block type="math_number" id="qU0B=-bkuwz|Z?=ct}P`">',
	'                        <field name="NUM">28</field>',
	'                      </block>',
	'                    </value>',
	'                  </block>',
	'                </value>',
	'                <statement name="DO0">',
	'                  <block type="variables_set" id="*7JEaf=7ZN.3gS^1P`V[">',
	'                    <field name="VAR">msg</field>',
	'                    <value name="VALUE">',
	'                      <block type="text" id="mtjpv[5kEU)3S7@r8|pA">',
	'                        <field name="TEXT">Hot! Hot! Hot!</field>',
	'                      </block>',
	'                    </value>',
	'                  </block>',
	'                </statement>',
	'                <statement name="ELSE">',
	'                  <block type="variables_set" id="VeTr4SM6H`szij]1nnOR">',
	'                    <field name="VAR">msg</field>',
	'                    <value name="VALUE">',
	'                      <block type="text" id="%sCO6G]#tTy@)%jzz`}k">',
	'                        <field name="TEXT">I love CPF.</field>',
	'                      </block>',
	'                    </value>',
	'                  </block>',
	'                </statement>',
	'                <next>',
	'                  <block type="variables_set" id="j77^.Z9t)XXY5SVZ-p@v">',
	'                    <field name="VAR">AOPstatus</field>',
	'                    <value name="VALUE">',
	'                      <block type="cpfaop_jsondata_upload" id="dVRBPZNkYYP1/dwU=4{O">',
	'                        <value name="RECORDID">',
	'                          <block type="variables_get" id="Zz_6CV=_2O._T#I8_(ps">',
	'                            <field name="VAR">index</field>',
	'                          </block>',
	'                        </value>',
	'                        <value name="VALUE">',
	'                          <block type="cpfaop_json_data" id="Ej+b5h*h:QR6[M~GD7Xu">',
	'                            <value name="VALUE1">',
	'                              <block type="variables_get" id="r#PnN@k:odbPL%I-t,N,">',
	'                                <field name="VAR">celsius</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="VALUE2">',
	'                              <block type="variables_get" id="%|(J1TQ^r/N|U9IGW/Jv">',
	'                                <field name="VAR">msg</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="VALUE3">',
	'                              <block type="variables_get" id="W@WO]l[Gi}9SU%{R#IR:">',
	'                                <field name="VAR">date</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <next>',
	'                      <block type="cpf_title_ui_set" id="s*@;9Wzw^Hep|c#Rg-3C">',
	'                        <value name="VALUE">',
	'                          <block type="text_join" id=":dWBeTk;pU/4L+S^V3hw">',
	'                            <mutation items="4"></mutation>',
	'                            <value name="ADD0">',
	'                              <block type="text" id="mi3*,f@?S3jDj%h]%[)+">',
	'                                <field name="TEXT">Upload to cloud</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="ADD1">',
	'                              <block type="variables_get" id="D@HZ|pM8*Ur3bZO;3@V*">',
	'                                <field name="VAR">index</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="ADD2">',
	'                              <block type="text" id="#Z+M~q:h!{RyLlp9s;,;">',
	'                                <field name="TEXT">-</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="ADD3">',
	'                              <block type="variables_get" id="p[r(as/`DCa1P2PD^+0Y">',
	'                                <field name="VAR">AOPstatus</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                        <next>',
	'                          <block type="cpfaop_content_ui_set" id="/q`,_Y3u3]Ef6e^(1k)O">',
	'                            <value name="VALUE">',
	'                              <block type="text_join" id="U2t(-sS2Hi9qqOA]`r!)">',
	'                                <mutation items="3"></mutation>',
	'                                <value name="ADD0">',
	'                                  <block type="text" id="P!8F`~4-s1po+;bN.9Fn">',
	'                                    <field name="TEXT">JSON content:</field>',
	'                                  </block>',
	'                                </value>',
	'                                <value name="ADD1">',
	'                                  <block type="text_newline" id="7M{)AcScK~[h2pacG4s?"></block>',
	'                                </value>',
	'                                <value name="ADD2">',
	'                                  <block type="cpfaop_json_data" id="ce/DpeF2`l2Jje[X!B.c">',
	'                                    <value name="VALUE1">',
	'                                      <block type="variables_get" id="8(c5q4=Ip,R?XG(n-+?%">',
	'                                        <field name="VAR">celsius</field>',
	'                                      </block>',
	'                                    </value>',
	'                                    <value name="VALUE2">',
	'                                      <block type="variables_get" id="#IrQQ0),{QPOi~;umd8r">',
	'                                        <field name="VAR">msg</field>',
	'                                      </block>',
	'                                    </value>',
	'                                    <value name="VALUE3">',
	'                                      <block type="variables_get" id="qfgdffCMmz.Edjld}[7P">',
	'                                        <field name="VAR">date</field>',
	'                                      </block>',
	'                                    </value>',
	'                                  </block>',
	'                                </value>',
	'                              </block>',
	'                            </value>',
	'                            <next>',
	'                              <block type="cpf_delay_time" id="lEH6as%xUTinwm.aErY8">',
	'                                <value name="VALUE">',
	'                                  <block type="math_number" id="pg]@O/gHPzy%E/+5-hh@">',
	'                                    <field name="NUM">1000</field>',
	'                                  </block>',
	'                                </value>',
	'                              </block>',
	'                            </next>',
	'                          </block>',
	'                        </next>',
	'                      </block>',
	'                    </next>',
	'                  </block>',
	'                </next>',
	'              </block>',
	'            </next>',
	'          </block>',
	'        </next>',
	'      </block>',
	'    </statement>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson6 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="cpf_title_ui_set" id="7Ot6U_[p!*heJ1E]YqZ9" x="38" y="38">',
	'    <value name="VALUE">',
	'      <block type="text" id="BSL03.NRQ|:?|65xb5AO">',
	'        <field name="TEXT">Downloading...</field>',
	'      </block>',
	'    </value>',
	'    <next>',
	'      <block type="controls_for" id="Zl*z^,=0dgX5BCeaEP*,">',
	'        <field name="VAR">index</field>',
	'        <value name="FROM">',
	'          <shadow type="math_number" id="*uyIrju).*aD[2Pg?.mC">',
	'            <field name="NUM">1</field>',
	'          </shadow>',
	'        </value>',
	'        <value name="TO">',
	'          <shadow type="math_number" id="%7]9TT(WlGXTtP:_~S8/">',
	'            <field name="NUM">10</field>',
	'          </shadow>',
	'        </value>',
	'        <value name="BY">',
	'          <shadow type="math_number" id="{HpR*(p-*DFg3i`#=212">',
	'            <field name="NUM">1</field>',
	'          </shadow>',
	'        </value>',
	'        <statement name="DO">',
	'          <block type="variables_set" id="%O7EzlZ=Tsk*VV`pN?Z%">',
	'            <field name="VAR">aop_obj</field>',
	'            <value name="VALUE">',
	'              <block type="cpfaop_jsondata_download" id="B}D7.qBdAvca;Eo:Y`.q">',
	'                <value name="RECORDID">',
	'                  <block type="variables_get" id="AtH+?BEK4?Lm~]o{%_.h">',
	'                    <field name="VAR">index</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'            <next>',
	'              <block type="cpfaop_content_ui_set" id="Z%2fG6DJcE39_J;eOS8c">',
	'                <value name="VALUE">',
	'                  <block type="text_join" id="I5y[6L)W^a%dG*|!FxAg">',
	'                    <mutation items="12"></mutation>',
	'                    <value name="ADD0">',
	'                      <block type="text" id="I-GS|cfGNer(Hf=bvlX.">',
	'                        <field name="TEXT">store</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD1">',
	'                      <block type="variables_get" id="1TOcb~AWE{Y=~O#.Tnd0">',
	'                        <field name="VAR">index</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD2">',
	'                      <block type="text_newline" id="azeF0,mq010}=?}Oe^Kl"></block>',
	'                    </value>',
	'                    <value name="ADD3">',
	'                      <block type="text" id="zK/!rKQUi0+?a1t_unSw">',
	'                        <field name="TEXT">Temperature=</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD4">',
	'                      <block type="cpfaop_jsondata_parse" id="Gv{]^0_fA6K,R,#Z24#f">',
	'                        <field name="VALUEID">value1</field>',
	'                        <value name="JSONDATA">',
	'                          <block type="variables_get" id="IvtJgi:CU*,7ie5jXsad">',
	'                            <field name="VAR">aop_obj</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD5">',
	'                      <block type="text_newline" id="sJQ|;Na!bV=?(jg!u?*Q"></block>',
	'                    </value>',
	'                    <value name="ADD6">',
	'                      <block type="text" id="%/vP#YWLhg-)DHDhdgug">',
	'                        <field name="TEXT">Message=</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD7">',
	'                      <block type="cpfaop_jsondata_parse" id=",]`3/Pbk%R6Xj=2(9r/=">',
	'                        <field name="VALUEID">value2</field>',
	'                        <value name="JSONDATA">',
	'                          <block type="variables_get" id="rK.0x1oEfsDtl%cemhmB">',
	'                            <field name="VAR">aop_obj</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD8">',
	'                      <block type="text_newline" id="j19FaX]Ff.EA+E|#6@]Y"></block>',
	'                    </value>',
	'                    <value name="ADD9">',
	'                      <block type="text" id="RHGmjWrO-`Fz02uK@gJ,">',
	'                        <field name="TEXT">date=</field>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD10">',
	'                      <block type="cpfaop_jsondata_parse" id=";nvv}3bTIma(faTZQlAy">',
	'                        <field name="VALUEID">value3</field>',
	'                        <value name="JSONDATA">',
	'                          <block type="variables_get" id=")%pU5nUZ=LbTb_YZynv;">',
	'                            <field name="VAR">aop_obj</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <value name="ADD11">',
	'                      <block type="text_newline" id="Q5RY~G0n4:%KQ{1#8ViD"></block>',
	'                    </value>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </next>',
	'          </block>',
	'        </statement>',
	'        <next>',
	'          <block type="cpf_title_ui_set" id="EAE3%iJIu(TOe34QC8y.">',
	'            <value name="VALUE">',
	'              <block type="text" id="y!vvfyv)J,.2l64!@Kx`">',
	'                <field name="TEXT">Download finished</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </next>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',
];

CPFArduino.Lesson7 = [
	'<xml xmlns="http://www.w3.org/1999/xhtml">',
	'  <block type="controls_for" id="ak,er}e5iZtwuFRTx{`D" x="38" y="38">',
	'    <field name="VAR">index</field>',
	'    <value name="FROM">',
	'      <shadow type="math_number" id="A3_;|nx8@yUaghmauND6">',
	'        <field name="NUM">1</field>',
	'      </shadow>',
	'    </value>',
	'    <value name="TO">',
	'      <shadow type="math_number" id="udCY#-N~z~X?{n9Sa34`">',
	'        <field name="NUM">10</field>',
	'      </shadow>',
	'    </value>',
	'    <value name="BY">',
	'      <shadow type="math_number" id="6GK?}}NYa/Cu#U]7IA:N">',
	'        <field name="NUM">1</field>',
	'      </shadow>',
	'    </value>',
	'    <statement name="DO">',
	'      <block type="variables_set" id=",}F:+r+rl]]{PVB*MEGm">',
	'        <field name="VAR">aop_obj</field>',
	'        <value name="VALUE">',
	'          <block type="cpfaop_jsondata_download" id="nMMTC`KgVM0BEu11+^9h">',
	'            <value name="RECORDID">',
	'              <block type="variables_get" id="|u0yk;vbgm4ka=o%-18F">',
	'                <field name="VAR">index</field>',
	'              </block>',
	'            </value>',
	'          </block>',
	'        </value>',
	'        <next>',
	'          <block type="variables_set" id="[I,8)caHaTy27u(ReAE-">',
	'            <field name="VAR">celsius</field>',
	'            <value name="VALUE">',
	'              <block type="cpfaop_jsondata_parse" id="o3nQg_nYUQ(AGW:Xy4kL">',
	'                <field name="VALUEID">value1</field>',
	'                <value name="JSONDATA">',
	'                  <block type="variables_get" id="T)A#SC}eP)@W}P^z,n}C">',
	'                    <field name="VAR">aop_obj</field>',
	'                  </block>',
	'                </value>',
	'              </block>',
	'            </value>',
	'            <next>',
	'              <block type="cpf_temperature_ui_set" id="VfXo%boBT#;M0vJ_InFG">',
	'                <value name="VALUE">',
	'                  <block type="variables_get" id="?mpkfIQ,}[^|L(9Mv_k+">',
	'                    <field name="VAR">celsius</field>',
	'                  </block>',
	'                </value>',
	'                <next>',
	'                  <block type="controls_if" id="[15,p/.oIX/Uz:L~8E*f">',
	'                    <mutation elseif="2" else="1"></mutation>',
	'                    <value name="IF0">',
	'                      <block type="logic_compare" id="3S,Okn5FZ!Kn[7o1Aw`y">',
	'                        <field name="OP">LTE</field>',
	'                        <value name="A">',
	'                          <block type="variables_get" id="6A-.rCD/3}V:k2]Ip}v4">',
	'                            <field name="VAR">celsius</field>',
	'                          </block>',
	'                        </value>',
	'                        <value name="B">',
	'                          <block type="math_number" id="Ot.b0@cDN:N[ERKkvYQ}">',
	'                            <field name="NUM">24</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <statement name="DO0">',
	'                      <block type="cpf_rgbled_set_colour" id="`dUmu_wc-)xCh^z98D/8">',
	'                        <value name="LEDCOLOUR">',
	'                          <block type="colour_picker" id="Q7|%wU4x_?J(xAUjhSF{">',
	'                            <field name="COLOUR">#000066</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </statement>',
	'                    <value name="IF1">',
	'                      <block type="logic_operation" id="m7@E1T+G=2J6^GT_i6(w">',
	'                        <field name="OP">AND</field>',
	'                        <value name="A">',
	'                          <block type="logic_compare" id="QD9(%e5YG.mFM.I`4y-p">',
	'                            <field name="OP">GT</field>',
	'                            <value name="A">',
	'                              <block type="variables_get" id="K!4x3Q1N4n3WSe%zJSTZ">',
	'                                <field name="VAR">celsius</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="B">',
	'                              <block type="math_number" id="pB.V)5FE3l;JOvED^sE9">',
	'                                <field name="NUM">24</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                        <value name="B">',
	'                          <block type="logic_compare" id="7C/xBaRQ+4FQ(=~J!tjT">',
	'                            <field name="OP">LTE</field>',
	'                            <value name="A">',
	'                              <block type="variables_get" id="rm6|(#[6c([yHipE=OCO">',
	'                                <field name="VAR">celsius</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="B">',
	'                              <block type="math_number" id="Jg+tW3I~/f;sj)HgSU5e">',
	'                                <field name="NUM">28</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <statement name="DO1">',
	'                      <block type="cpf_rgbled_set_colour" id="F=QRqvb],Cf*n!M`wM_T">',
	'                        <value name="LEDCOLOUR">',
	'                          <block type="colour_picker" id="WRW3BGmeWyZ?69ZKh^3n">',
	'                            <field name="COLOUR">#006600</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </statement>',
	'                    <value name="IF2">',
	'                      <block type="logic_operation" id=":W%FmdzJA,KmU;v(|I64">',
	'                        <field name="OP">AND</field>',
	'                        <value name="A">',
	'                          <block type="logic_compare" id="X.+!}mu4A!xqdWZqlR4m">',
	'                            <field name="OP">GT</field>',
	'                            <value name="A">',
	'                              <block type="variables_get" id="U/@q2FFN(SwelyFY~UF5">',
	'                                <field name="VAR">celsius</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="B">',
	'                              <block type="math_number" id="{`M69lo*dN]Z2qVRgs=3">',
	'                                <field name="NUM">28</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                        <value name="B">',
	'                          <block type="logic_compare" id="vQ~%VWIlhAtaGdhdvN#u">',
	'                            <field name="OP">LTE</field>',
	'                            <value name="A">',
	'                              <block type="variables_get" id="E(UV{:1p!plJG~K.%c2a">',
	'                                <field name="VAR">celsius</field>',
	'                              </block>',
	'                            </value>',
	'                            <value name="B">',
	'                              <block type="math_number" id="*;HsVVE2MjB#FT6z9oA@">',
	'                                <field name="NUM">32</field>',
	'                              </block>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </value>',
	'                    <statement name="DO2">',
	'                      <block type="cpf_rgbled_set_colour" id="6Nrh8##elB7W~A*[M/]v">',
	'                        <value name="LEDCOLOUR">',
	'                          <block type="colour_rgb" id="1_+GS,@3m)ZSa*{5Mrs4">',
	'                            <value name="RED">',
	'                              <shadow type="math_number" id="E0TS`Z?0S{,(YB7y7m.|">',
	'                                <field name="NUM">250</field>',
	'                              </shadow>',
	'                            </value>',
	'                            <value name="GREEN">',
	'                              <shadow type="math_number" id="~zwV7wlR]SD4lSOh32Tj">',
	'                                <field name="NUM">150</field>',
	'                              </shadow>',
	'                            </value>',
	'                            <value name="BLUE">',
	'                              <shadow type="math_number" id="~w[mg|4##0k?VNU=f6Yz">',
	'                                <field name="NUM">30</field>',
	'                              </shadow>',
	'                            </value>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </statement>',
	'                    <statement name="ELSE">',
	'                      <block type="cpf_rgbled_set_colour" id="x%-u^X-a[3UVo{cFgz)V">',
	'                        <value name="LEDCOLOUR">',
	'                          <block type="colour_picker" id=":#MR~E2HZBo|-T-/wFoZ">',
	'                            <field name="COLOUR">#ff0000</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </statement>',
	'                    <next>',
	'                      <block type="cpf_delay_time" id="8_ILig#1+1^z1sO:qn0X">',
	'                        <value name="VALUE">',
	'                          <block type="math_number" id="tPzJtS+R]tnU^NW/;d%(">',
	'                            <field name="NUM">2000</field>',
	'                          </block>',
	'                        </value>',
	'                      </block>',
	'                    </next>',
	'                  </block>',
	'                </next>',
	'              </block>',
	'            </next>',
	'          </block>',
	'        </next>',
	'      </block>',
	'    </statement>',
	'    <next>',
	'      <block type="cpf_title_ui_set" id="=U-AalVgobSC3_E5_g(e">',
	'        <value name="VALUE">',
	'          <block type="text" id=";9iAE[]pg9!n690x9J]I">',
	'            <field name="TEXT">Download finished</field>',
	'          </block>',
	'        </value>',
	'      </block>',
	'    </next>',
	'  </block>',
	'</xml>',                                                                 
];                                                                                                     

CPFArduino.Lesson8 = [
 '<xml xmlns="http://www.w3.org/1999/xhtml"> ',
 '  <block type="cpf_title_ui_set" id=",XBlLutgXoyJOz#5yNA7" x="138" y="13">  ',
 '    <value name="VALUE"> ',
 '      <block type="text" id="?sWc#O1=%,4CDg}cbo6|"> ',
 '        <field name="TEXT">Night Alarm</field>  ',
 '      </block>   ',
 '    </value>    ',
 '    <next>      ',
 '      <block type="controls_if" id="P}0Qew,EZf;Y!{u?h#:O">  ',
 '        <mutation else="1"></mutation>       ',
 '        <value name="IF0">     ',
 '          <block type="logic_compare" id="=Ch:Qpm(0D[JLLZc42EJ">  ',
 '            <field name="OP">LT</field>  ',
 '            <value name="A">  ',
 '              <block type="cpf_lightsensor_get" id="5v/KlySvF/AiwChygyj]"></block>  ',
 '            </value>           ',
 '            <value name="B">    ',
 '              <block type="math_number" id="NwR%+QY#Kt-(9(7RC)Ho">   ',
 '                <field name="NUM">500</field>  ',
 '              </block>  ',
 '            </value>  ',
 '          </block>   ',
 '        </value>     ',
 '        <statement name="DO0">  ',
 '          <block type="cpf_led_manaul_set" id="j*/(!OrLw~rQaB+AaHV?">   ',
 '            <value name="VALUE">   ',
 '              <block type="cpf_led_onoff" id="qoVjYqjRjfzIl220!KF/">  ',
 '                <field name="BOOL">ON</field>   ',
 '              </block>   ',
 '            </value>    ',
 '            <next>    ',
 '              <block type="controls_if" id="Sa`U/3%_;`)+dW!u+UIX">  ',
 '                <value name="IF0">    ',
 '                  <block type="logic_compare" id="PYqeh5?5}_+jl^XfZEJt">   ',
 '                    <field name="OP">EQ</field>   ',
 '                    <value name="A">    ',
 '                      <block type="cpf_pir_get" id="r7{4U)1Rj{_aOsGp/MD`">  ',
 '                        <field name="PIN">D6</field>   ',
 '                      </block>  ',
 '                    </value>    ',
 '                    <value name="B">  ',
 '                      <block type="inout_highlow" id="~w7W6};h|@.R-ex;?3-9">  ',
 '                        <field name="BOOL">1</field>   ',
 '                      </block>   ',
 '                    </value>  ',
 '                  </block>  ',
 '                </value>  ',
 '                <statement name="DO0">   ',
 '                  <block type="controls_repeat_ext" id=",:Zxd,U#;osb.iV(`lzL">  ',
 '                    <value name="TIMES"> ',
 '                      <shadow type="math_number" id="lcxBaq!OP|m-tiD[D2~]">  ',
 '                        <field name="NUM">5</field> ',
 '                      </shadow>    ',
 '                    </value>  ',
 '                    <statement name="DO"> ',
 '                      <block type="cpf_rgbled_set_colour" id="yuDN{kAQ)]A6V-|!-kgo">  ',
 '                        <value name="LEDCOLOUR">   ',
 '                          <block type="colour_picker" id="cnF=ma.uJQ#LQ4|4;/Tc"> ',
 '                            <field name="COLOUR">#ff0000</field>   ',
 '                          </block>    ',
 '                        </value>     ',
 '                        <next>    ',
 '                          <block type="cpf_servo_move" id="XnC%EX0_`;@{5f6.)v}9">  ',
 '                            <field name="PIN">D4</field>    ',
 '                            <value name="DEGREE">    ',
 '                              <block type="math_number" id="qF_cE(Q^91MDSxaCXll[">   ',
 '                                <field name="NUM">10</field>    ',
 '                              </block>  ',
 '                            </value>     ',
 '                            <value name="DELAY_TIME">   ',
 '                              <block type="math_number" id="]oV(),b@Sqw}+=)1!7%_"> ',
 '                                <field name="NUM">0</field>  ',
 '                              </block>    ',
 '                            </value>   ',
 '                            <next>     ',
 '                              <block type="cpf_buzzer_tone" id="v5jX_`rAXCLg2WiL=Y!S">  ',
 '                                <field name="PIN">D5</field>       ',
 '                                <field name="FREQ">523</field>   ',
 '                                <next>     ',
 '                                  <block type="cpf_delay_time" id="dShQYcU#a;Zf+PFY!.CF">  ',
 '                                    <value name="VALUE">   ',
 '                                      <block type="math_number" id="_jPMt_2z!i|J((V+?daQ">  ',
 '                                        <field name="NUM">250</field>  ',
 '                                      </block>   ',
 '                                    </value>    ',
 '                                    <next>    ',
 '                                      <block type="cpf_servo_move" id="lvfs4_B~(0:YNMA?j#,I">  ',
 '                                        <field name="PIN">D4</field>    ',
 '                                        <value name="DEGREE">   ',
 '                                          <block type="math_number" id="CS^5sb[esFB8)q/Z.;1C">    ',
 '                                            <field name="NUM">170</field>    ',
 '                                          </block>    ',
 '                                        </value>     ',
 '                                        <value name="DELAY_TIME">  ',
 '                                          <block type="math_number" id="]BPeb5Cf?-r-8}Cd]k~K">   ',
 '                                            <field name="NUM">0</field>  ',
 '                                          </block>    ',
 '                                        </value>    ',
 '                                        <next>      ',
 '                                          <block type="cpf_buzzer_tone" id="m}}S)nKq5nMWTn/)uxX2">    ',
 '                                            <field name="PIN">D5</field>      ',
 '                                            <field name="FREQ">523</field>   ',
 '                                            <next>    ',
 '                                              <block type="cpf_delay_time" id="?}n[oJ[d9CKezif(b,M~">     ',
 '                                                <value name="VALUE">    ',
 '                                                  <block type="math_number" id=")rB%#X(Ao7bX5sY5X/{l">    ',
 '                                                    <field name="NUM">250</field>   ',
 '                                                  </block>    ',
 '                                                </value>    ',
 '                                              </block>     ',
 '                                            </next>      ',
 '                                          </block>     ',
 '                                        </next>      ',
 '                                      </block>            ',
 '                                    </next>     ',
 '                                  </block>   ',
 '                                </next>    ',
 '                              </block>    ',
 '                            </next>      ',
 '                          </block>      ',
 '                        </next>       ',
 '                      </block>       ',
 '                    </statement>      ',
 '                    <next>       ',
 '                      <block type="cpf_no_tone" id="I6DQHc~a.?F#0#Z^q!@5">    ',
 '                        <field name="PIN">D5</field>   ',
 '                        <next>     ',
 '                          <block type="cpf_rgbled_set_colour" id="c3ir@E{^NatjsLHIgub9">   ',
 '                            <value name="LEDCOLOUR">   ',
 '                              <block type="colour_picker" id="00;pRso=DxqMh-5[94cS">  ',
 '                                <field name="COLOUR">#33ff33</field>  ',
 '                              </block>    ',
 '                            </value>    ',
 '                          </block>   ',
 '                        </next>    ',
 '                      </block>     ',
 '                    </next>        ',
 '                  </block>   ',
 '                </statement>   ',
 '              </block>   ',
 '            </next>     ',
 '          </block>      ',
 '        </statement>   ',
 '        <statement name="ELSE">    ',
 '          <block type="cpf_led_manaul_set" id=",X-^?-:QM:,yV!m_`{4Z">    ',
 '            <value name="VALUE">         ',
 '              <block type="cpf_led_onoff" id="N9lYY7e22`Q,aCT7(,QV">   ',
 '                <field name="BOOL">OFF</field>    ',
 '              </block>      ',
 '            </value>      ',
 '          </block>      ',
 '        </statement>     ',
 '        <next>        ',
 '          <block type="cpf_control_repeat" id="`,]5RPN@~/m9O1fa8,^1"></block> ',
 '        </next>     ',
 '      </block>    ',
 '    </next>     ',
 '  </block>   ',
 '</xml>     ',
];

CPFArduino.Lesson9 = [
'<xml xmlns="http://www.w3.org/1999/xhtml">',
 ' <block type="cpf_title_ui_set" id="gy`d{(RI8Z5U9%9M^@y4" x="238" y="137">',
  '  <value name="VALUE">',
   '   <block type="text" id="C2i!lp0zxrZ*yva(FB0Y">',
    '    <field name="TEXT">Humidity Detector</field>',
     ' </block>',
    '</value>',
   ' <next>',
   '   <block type="controls_if" id="Dk[lZ;bcSYOdF8`v^b0u">',
   '     <mutation elseif="1" else="1"></mutation>',
   '     <value name="IF0">',
   '       <block type="logic_compare" id="+vjAn/G!~az1p2F(:Msr">',
   '         <field name="OP">LT</field>',
   '         <value name="A">',
   '           <block type="cpf_sensor_dht11" id="h3gT=F%k!!?fIB0b.F`#">',
    '            <field name="PIN">A2</field>',
    '            <field name="DATATYPE">dht11humi</field>',
    '          </block>',
    '        </value>',
   '         <value name="B">',
    '          <block type="math_number" id="Oq{}LJy(4U3B9zFJrMcz">',
   '             <field name="NUM">40</field>',
   '           </block>',
     '       </value>',
     '     </block>',
     '   </value>',
    '    <statement name="DO0">',
    '      <block type="cpf_i2clcd_set_backlight" id="RS]=L^Wba7GMr]~}u(Z4">',
      '      <value name="RED">',
      '        <block type="math_number" id="g%5c]@iMxZ=A64m:@YYw">',
        '        <field name="NUM">255</field>',
       '       </block>',
          '  </value>',
         '   <value name="GREEN">',
        '      <block type="math_number" id="DG{2?|2g1RX:4[SacjZJ">',
        '        <field name="NUM">0</field>',
       '       </block>',
       '     </value>',
        '    <value name="BLUE">',
       '       <block type="math_number" id="wyW0SS_nWs=|z!Wq-}/o">',
      '          <field name="NUM">0</field>',
      '        </block>',
      '      </value>',
       '     <next>',
          '    <block type="cpf_i2clcd_print" id="PwQmDiT[w`;R3eIev{+d">',
          '      <value name="COL">',
          '        <block type="math_number" id="}jzX2#in1P[N8;~ZCeI*">',
          '          <field name="NUM">0</field>',
          '        </block>',
           '     </value>',
          '      <value name="ROW">',
          '        <block type="math_number" id="XT1B3oxV:`*B5Ve8toNc">',
          '          <field name="NUM">0</field>',
          '        </block>',
          '      </value>',
          '      <value name="PRINT">',
          '        <block type="text" id="bF}ym*[%]-;GxDWnJAap">',
          '          <field name="TEXT">too dry</field>',
          '        </block>',
            '    </value>',
           '   </block>',
          '  </next>',
     '     </block>',
      '  </statement>',
      '  <value name="IF1">',
      '    <block type="logic_compare" id="-{g)z`!Loj@i=?sO7z^N">',
      '      <field name="OP">GT</field>',
       '     <value name="A">',
        '      <block type="cpf_sensor_dht11" id="UTQb|lP/+3Q=mNR;r`iA">',
        '        <field name="PIN">A2</field>',
        '        <field name="DATATYPE">dht11humi</field>',
        '      </block>',
         '   </value>',
        '    <value name="B">',
           '   <block type="math_number" id="HcH@h2n_U5US,/cU2lO_">',
          '      <field name="NUM">60</field>',
        '      </block>',
       '     </value>',
      '    </block>',
     '   </value>',
     '   <statement name="DO1">',
     '     <block type="cpf_i2clcd_set_backlight" id="7%uL@/kEFt=gx,-6=he2">',
     '       <value name="RED">',
     '         <block type="math_number" id="rfTOe#;OU`;s,:@GE@+(">',
      '          <field name="NUM">0</field>',
      '        </block>',
      '      </value>',
      '      <value name="GREEN">',
        '      <block type="math_number" id="+Svo^[LRD/,00sq=R`vk">',
           '     <field name="NUM">0</field>',
          '    </block>',
         '   </value>',
        '    <value name="BLUE">',
        '      <block type="math_number" id="_w;5wTH?cG(Y%p+wa)iK">',
         '       <field name="NUM">255</field>',
        '      </block>',
        '    </value>',
        '    <next>',
         '     <block type="cpf_i2clcd_print" id="qtnY;Xsg?u9!K`o3/7DR">',
        '        <value name="COL">',
         '         <block type="math_number" id="o[;qLDi0%;]O4^T;U9so">',
              '      <field name="NUM">0</field>',
            '      </block>',
            '    </value>',
           '     <value name="ROW">',
          '        <block type="math_number" id="k2|=+8@A~D+@+JoU:np5">',
            '        <field name="NUM">0</field>',
           '       </block>',
           '     </value>',
            '    <value name="PRINT">',
            '      <block type="text" id="K%/fFzjJ},U/P]Jrt#t7">',
            '        <field name="TEXT">it is wet</field>',
              '    </block>',
            '    </value>',
          '    </block>',
         '   </next>',
         ' </block>',
      '  </statement>',
       ' <statement name="ELSE">',
      '    <block type="cpf_i2clcd_set_backlight" id="clohDehHEFeap)k?L|h;">',
      '      <value name="RED">',
       '       <block type="math_number" id="My6?Cjo4r@EP_17)`d.Z">',
        '        <field name="NUM">0</field>',
       '       </block>',
       '     </value>',
       '     <value name="GREEN">',
         '     <block type="math_number" id="75Mn)NeDA(i9Bir.sCc+">',
         '       <field name="NUM">255</field>',
       '       </block>',
       '     </value>',
       '     <value name="BLUE">',
      '        <block type="math_number" id="|QNw!my0K=L!|m:Bt:a9">',
       '         <field name="NUM">0</field>',
       '       </block>',
        '    </value>',
          '  <next>',
          '    <block type="cpf_i2clcd_print" id="T-sT2}J{4]~x+@yZXV2=">',
         ' <value name="COL">',
          '        <block type="math_number" id="qHvdWKLts*r!?VnyZ~xy">',
           '         <field name="NUM">0</field>',
             '     </block>',
             '   </value>',
             '   <value name="ROW">',
             '     <block type="math_number" id="vyz?b_1rc5JAmLrRwwou">',
             '       <field name="NUM">0</field>',
              '    </block>',
              '  </value>',
             '   <value name="PRINT">',
              '    <block type="text" id="1n[96j*IG9.HP8=K8d=T">',
             '       <field name="TEXT">Comfortable!</field>',
              '    </block>',
               ' </value>',
              '  <next>',
               '   <block type="cpf_i2clcd_print" id="G`?dQe#}g_KzP^Q!VXy-">',
              '      <value name="COL">',
               '       <block type="math_number" id="SM@YjW@12Jm.kpUQOalJ">',
                       ' <field name="NUM">2</field>',
                '      </block>',
                '    </value>',
                 '   <value name="ROW">',
               '       <block type="math_number" id="+uY4b3N%D1YyWDLNTiE:">',
                      '  <field name="NUM">1</field>',
                  '    </block>',
                  '  </value>',
                 '   <value name="PRINT">',
                 '     <block type="text" id="qZo]R~i-f)IDo,p;O@x8">',
                 '       <field name="TEXT">Go out to play</field>',
                '      </block>',
                '    </value>',
               '   </block>',
               ' </next>',
           '   </block>',
          '  </next>',
        '  </block>',
      '  </statement>',
      '  <next>',
         ' <block type="cpf_control_repeat" id="QEb2OyhUn/vL7w[:d.Xw"></block>',
        '</next>',
   '   </block>',
 '   </next>',
'  </block>',
'</xml>',
];