var MSG = {
  title: "WebCPF",
  blocks: "Lesson",
  xmlCloudUploadTooltip: "Save or load program",
  linkTooltip: "Load default program",
  runTooltip: "Run the program",
  undoTooltip: "Roll back to the previous action",
  redoTooltip: "Redo the previous action",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catInOut:"IN/OUT",
  catDigital:"Digital",
  catAnalog:"Analog",

  catCPF: "CPF",
  catHardwaeDevices: "Sensor Modules",
  catCPFDevices: "CPF Devices",
  catCPFLightsensor: "Light",
  catCPFTemperature: "Temperature",
  catCPFFan: "Fan",
  catCPFRGBled: "RGB LED",  
  catCPFLed: "White LED",
  catCPFUI: "CPF UI",
  catCPFAOP: "Cloud Service",
  catCPFUIFan: "Fan",
  catCPFInDevices: "Input Devices",
  catCPFInEnvironment: "Environment Sensors",
  catCPFInGas: "Gas Sensors",
  catCPFInSwitch: "Switchs",
  catCPFInIRPowerSensor: "IR & others Sensors",
  catCPFOutDevices: "Output Devices",
  catCPFOutSoundLight: "Sound & Light",
  catCPFOutRelay: "Relay Devices",
  catCPFOutMotors: "Motors",
  catCPFOutDisplay: "Display",
  
  listVariable: "list",
  textVariable: "text",  
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  
  lessonName: ["Lesson1 Smart Light", "Lesson2 Remote Fan", "Lesson3 Ramen Cooler", "Lesson4 UFO"],
  ControlPanelTitle: "CPF Control Panel",
  ScanPanelTitle: "Searching",
  LoginTitle: "Choose account for CloudProfessor",
  LoginAct: "Email account：",
  LoginButton: "Login",
  CloudListTitle: "&nbsp&nbsp&nbsp&nbspSave or load default program",
  CpfIcon: "CloudProfessor",
  CpfMacTitle: "ID:",
  CpfVerTitle: "System Version:",
  CpfIpTitle: "IP Address:",
  CpfWifiTitle: "Wi-Fi:",
  CpfSearch: "Pair with CloudProfessor",
  
  LoginSuccess: "Login Successed",
  LoginFailed: "Couldn't find your Email account",
  None: 'none',
  SaveCode: "Save",
  PleaseLogin: "Please login",
  SaveConfirm: "Do you want to save and overwrite?",
  SaveSuccess: "Save complete！",
  DownloadConfirm: "Do you want to load this program? It will overwrite your current program.",
  
  //cpfconnect.js
  ChooseButton: "Select",
  ChooseTitle: "Select your CPF",
  SearchOver: "Search Complete",
  PairTitle: "Select your CPF",
  PairSuccess: "CPF setup complete！",
  ReloadMsg: "sec, System will reload.",
  Searching: "Searching"
};
