var MSG = {
  title: "WebCPF",
  blocks: "<< Bloques",
  linkTooltip: "Guarda conexión a los bloques.",
  runTooltip: "Ejecute el programa definido por los bloques en el área de trabajo.",
  undoTooltip: "Roll back to the previous action",
  redoTooltip: "Redo the previous action",
  badCode: "Error del programa:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Secuencias",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  catInOut:"IN/OUT",
  catDigital:"Digital",
  catAnalog:"Analog",
  catCPF: "CPF",
  catHardwaeDevices: "Sensor Modules",
  catCPFDevices: "Dispositivos CPF",
  catCPFLightsensor: "Luz",
  catCPFTemperature: "Temperatura",
  catCPFFan: "Ventilador",
  catCPFRGBled: "LED RGB",  
  catCPFLed: "LED blanco",
  catCPFUI: "Interfaz del CPF",
  catCPFAOP: "Nube AOP",
  catCPFUIFan: "Ventilador",
  catCPFInDevices: "Input Devices",
  catCPFInEnvironment: "Environment Sensors",
  catCPFInGas: "Gas Sensors",
  catCPFInSwitch: "Joysticks & Switchs",
  catCPFInIRPowerSensor: "IR & others Sensors",
  catCPFOutDevices: "Output Devices",
  catCPFOutSoundLight: "Sound & Light",
  catCPFOutRelay: "Relay Devices",
  catCPFOutMotors: "Motors",
  catCPFOutDisplay: "Display",
  
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML."
};
