var MSG = {
  title: "WebCPF",
  blocks: "<< Blocchi",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Esegui il programma definito dai blocchi nell'area di lavoro.",
  undoTooltip: "Roll back to the previous action",
  redoTooltip: "Redo the previous action",
  badCode: "Errore programma:\n%1",
  timeout: "È stato superato il numero massimo consentito di interazioni eseguite.",
  trashTooltip: "Elimina tutti i blocchi.",
  catLogic: "Logica",
  catLoops: "Cicli",
  catMath: "Matematica",
  catText: "Testo",
  catLists: "Elenchi",
  catColour: "Colore",
  catVariables: "Variabili",
  catFunctions: "Funzioni",
  catInOut:"IN/OUT",
  catDigital:"Digital",
  catAnalog:"Analog",
  catCPF: "CPF",
  catHardwaeDevices: "Sensor Modules",
  catCPFDevices: "Dispositivi CPF",
  catCPFLightsensor: "Luce",
  catCPFTemperature: "Temepratura",
  catCPFFan: "ventola",
  catCPFRGBled: "LED RGB",  
  catCPFLed: "LED Bianco",
  catCPFUI: "CPF UI",
  catCPFAOP: "AOP Cloud",
  catCPFUIFan: "Ventola",
  catCPFInDevices: "Input Devices",
  catCPFInEnvironment: "Environment Sensors",
  catCPFInGas: "Gas Sensors",
  catCPFInSwitch: "Switchs",
  catCPFInIRPowerSensor: "IR & others Sensors",
  catCPFOutDevices: "Output Devices",
  catCPFOutSoundLight: "Sound & Light",
  catCPFOutRelay: "Relay Devices",
  catCPFOutMotors: "Motors",
  catCPFOutDisplay: "Display",
  
  listVariable: "elenco",
  textVariable: "testo",
  httpRequestError: "La richiesta non è stata soddisfatta.",
  linkAlert: "Condividi i tuoi blocchi con questo collegamento:\n\n%1",
  hashError: "Mi spiace, '%1' non corrisponde ad alcun programma salvato.",
  xmlError: "Non è stato possibile caricare il documento.  Forse è stato creato con una versione diversa di Blockly?",
  badXml: "Errore durante l'analisi XML:\n%1\n\nSeleziona 'OK' per abbandonare le modifiche o 'Annulla' per continuare a modificare l'XML."
};
