var MSG = {
  title: "WebCPF",
  blocks: "課程：",
  xmlCloudUploadTooltip: "儲存或載入程式",
  linkTooltip: "回復到初始積木狀態。",
  runTooltip: "於工作區中執行積木組所定義的程式。",
  undoTooltip: "回復上一個動作",
  redoTooltip: "重複執行上一個動作",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數。",
  trashTooltip: "捨棄所有積木。",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "列表",
  catColour: "顏色",
  catVariables: "變量",
  catFunctions: "流程",
  catInOut:"腳位輸入/輸出",
  catDigital:"數位",
  catAnalog:"類比",
  
  catCPF: "CPF",
  catHardwaeDevices: "感測模組",
  catCPFDevices: "CPF裝置",
  catCPFLightsensor: "光感測",
  catCPFTemperature: "溫度感測",
  catCPFFan: "風扇控制",
  catCPFRGBled: "彩色LED",
  catCPFLed: "白光LED",
  catCPFUI: "CPF介面",
  catCPFAOP: "雲端服務",
  catCPFUIFan: "風扇",
  catCPFInDevices: "輸入裝置",
  catCPFInEnvironment: "環境感測裝置",
  catCPFInGas: "氣體感測裝置",
  catCPFInSwitch: "開關",
  catCPFInIRPowerSensor: "紅外線及其它感測裝置",
  catCPFOutDevices: "輸出裝置",
  catCPFOutSoundLight: "聲光裝置",
  catCPFOutRelay: "繼電器裝置",
  catCPFOutMotors: "馬達",
  catCPFOutDisplay: "顯示裝置",

  listVariable: "列表",
  textVariable: "文字",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。",
  
  lessonName: ["Lesson1 智慧光感燈", "Lesson2 CPF遙控風扇", "Lesson3 CPF泡麵降溫器", "Lesson4 CPF飛碟"],
  ControlPanelTitle: "CPF 控制面板",
  ScanPaneltTitle: "搜尋中",
  LoginTitle: "請選擇登入的帳號",
  LoginAct: "信箱帳號：",
  LoginButton: "登入",
  CloudListTitle: "&nbsp&nbsp&nbsp&nbsp儲存或載入程式",
  CpfIcon: "雲教授",
  CpfMacTitle: "編號：",
  CpfVerTitle: "系統版本：",
  CpfIpTitle: "IP位址：",
  CpfWifiTitle: "Wi-Fi：",
  CpfSearch: "配對雲教授",
  
  LoginSuccess: "登入成功",
  LoginFailed: "輸入的帳號有誤",
  None: '無',
  SaveCode: "儲存",
  PleaseLogin: "請先登入帳號",
  SaveConfirm: "是否確定儲存及覆蓋?",
  SaveSuccess: "儲存成功！",
  DownloadConfirm: "是否確定載入此程式,這將會覆蓋您目前的程式?",
  
  //cpfconnect.js
  ChooseButton: "選擇",
  ChooseTitle: "請選擇您的雲教授",
  SearchOver: "搜尋完成",
  PairTitle: "配對雲教授",
  PairSuccess: "配對成功！",
  ReloadMsg: "秒後系統自動重新載入.",
  Searching: "搜尋中"
  
};
